#
# Copyright (C) 2022 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

agents:
  - name: "PersonAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: false

  - name: "FriendshipAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: false

  - name: "MarriageAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: false

  - name: "ParenthoodAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: false

  - name: "MaritalStatusAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

  - name: "GrandparenthoodAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

  - name: "LineageAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

  - name: "NationalityAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

  - name: "CitizenshipAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

  - name: "CoupleFriendshipAgent"
    action: "doAction"
    actionsPerIteration: 1
    trace: true

traceSampling:
  # Options: `"every"` for every K traces; `"log"` for logarithm with base N
  function: "every"
  arg: 1
  databaseName: "simulation"
  partitions: 1
  recreateDatabase: true
  parallelism: 1

run:
  randomSeed: 1
  iterations: 6
  databaseName: "simulation-reasoning"

model:
  populationGrowth: 2
  ageOfFriendship: 1
  ageOfAdulthood: 2
  yearsBeforeParenthood: 1
